var data = [{
              "Alias": "Hannah Abbott ",
              "Degree": "Master in Science",
              "Major": "Computer Science",
              "interest, hobbies": "Machine learning, crypto currencies, video games, programming in general",
              "expecting": "learn how to best visualize information to understand data",
              "InfoVis": 3,
              "statistical": 6,
              "mathematics": 2,
              "artistry": 6,
              "computer usage": 10,
              "programming": 10,
              "GFX prog.": 2,
              "HCI prog.": 8,
              "UX eval.": 1,
              "communication": 6,
              "collaboration": 8,
              "code repository": 10
            },
            {
              "Alias": "Ludo Bagman ",
              "Degree": "Master in Science",
              "Major": "Human-Computer Interaction",
              "interest, hobbies": "I am interested in music, art and media. I play piano; love skiing.",
              "expecting": "I expect exactly to learn how to visualize and envision information in nice and interesting way. ",
              "InfoVis": 2,
              "statistical": 4,
              "mathematics": 3,
              "artistry": 9,
              "computer usage": 3,
              "programming": 1,
              "GFX prog.": 1,
              "HCI prog.": 1,
              "UX eval.": 7,
              "communication": 10,
              "collaboration": 9,
              "code repository": 1
            },
            {
              
              "Alias": "Bathilda Bagshot ",
              "Degree": "Bachelor in Science",
              "Major": "Nuclear, Plasma, and Radiological Engineering (focus in microelectronics and nanotechnology)",
              "interest, hobbies": "I enjoy learning about foreign cultures and languages, biking, tennis, classic movies, traveling, and organizing lots of different things (more of an OCD sort of thing, but very helpful). Recently I have been thinking a lot about the importance of design in engineering in general, be it a physical object like a cell phone or something more abstract like a computer algorithm. Smooth, effective design is satisfying, and fits well in a sleek, wired, progressive culture such as that of Sweden.",
              "expecting": "I want to learn how to manipulate data into interactive, smooth-running informatics. It is something I have been interested in for a while, and to me it may be a useful skill in the future.",
              "InfoVis": 2,
              "statistical": 3,
              "mathematics": 6,
              "artistry": 9,
              "computer usage": 5,
              "programming": 3,
              "GFX prog.": 3,
              "HCI prog.": 3,
              "UX eval.": 4,
              "communication": 8,
              "collaboration": 8,
              "code repository": 2
            },
            {
              
              "Alias": "Katie Bell ",
              "Degree": "Bachelor in Science",
              "Major": "Computer Science",
              "interest, hobbies": "Basketball",
              "expecting": "Better understanding for big data",
              "InfoVis": 3,
              "statistical": 5,
              "mathematics": 5,
              "artistry": 3,
              "computer usage": 6,
              "programming": 5,
              "GFX prog.": 4,
              "HCI prog.": 3,
              "UX eval.": 4,
              "communication": 7,
              "collaboration": 8,
              "code repository": 7
            },
            {
              
              "Alias": "Cuthbert Binns",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": "Music making, creative coding",
              "expecting": "Learn: How to approach and complete beautiful, useful and interesting visualizations of data; to be able to enable/facilitate extraction of new meaning from a collection of data. I would like to learn to visualize audio or other interesting (interactive) data sets. Visualize so it looks taken from nature (behaviour steering). I expect to learn stuff i really wanna learn and not do stuff i already know. \nUse: i wanna use it to learn do  beautiful and eye-opening visualizations, to learn tools that i can be creative with. ",
              "InfoVis": 2,
              "statistical": 1,
              "mathematics": 3,
              "artistry": 7,
              "computer usage": 8,
              "programming": 6,
              "GFX prog.": 2,
              "HCI prog.": 6,
              "UX eval.": 5,
              "communication": 9,
              "collaboration": 9,
              "code repository": 2
            },
            {
              
              "Alias": "Phineas Nigellus Black",
              "Degree": "Master in Science",
              "Major": "Computer Science",
              "interest, hobbies": "Gaming",
              "expecting": "I'm not sure, but i'm sure that I want to expand my knowledge so that I can narrow down what I want to do in the future. ",
              "InfoVis": 3,
              "statistical": 3,
              "mathematics": 5,
              "artistry": 1,
              "computer usage": 9,
              "programming": 2,
              "GFX prog.": 1,
              "HCI prog.": 1,
              "UX eval.": 5,
              "communication": 8,
              "collaboration": 10,
              "code repository": 3
            },
            {
              
              "Alias": "Sirius Black",
              "Degree": "Master in Science",
              "Major": "Human-Computer Interaction, Media Technology, Physical Interaction design",
              "interest, hobbies": "",
              "expecting": "How to visualise in a clean/neat way on the web  and learn different frameworks/libraries, and use the knowledge in perfecting my future employment as front end developer",
              "InfoVis": 7,
              "statistical": 2,
              "mathematics": 6,
              "artistry": 3,
              "computer usage": 9,
              "programming": 6,
              "GFX prog.": 5,
              "HCI prog.": 6,
              "UX eval.": 4,
              "communication": 9,
              "collaboration": 9,
              "code repository": 8
            },
            {
              
              "Alias": "Amelia Bones ",
              "Degree": "Master in Science",
              "Major": "Computer Science, Human-Computer Interaction, Industrial management",
              "interest, hobbies": "I love marketing. I run a small agency studentutvecklarna.se",
              "expecting": "How to visualize vast amount of complicated numbers so that they make sense. For example marketing data",
              "InfoVis": 2,
              "statistical": 2,
              "mathematics": 3,
              "artistry": 2,
              "computer usage": 3,
              "programming": 1,
              "GFX prog.": 2,
              "HCI prog.": 1,
              "UX eval.": 2,
              "communication": 9,
              "collaboration": 5,
              "code repository": 1
            },
            {
              
              "Alias": "Susan Bones ",
              "Degree": "Master in Science",
              "Major": "Computer Science",
              "interest, hobbies": "I'm good at problem solving. I feel calm when I settle down in front of a computer and start working.",
              "expecting": "I would like to learn how complicated data would be graphically presented to audience, and I wish this would help when I need to show some information to users efficiently when I design a game or software.",
              "InfoVis": 6,
              "statistical": 4,
              "mathematics": 7,
              "artistry": 3,
              "computer usage": 9,
              "programming": 7,
              "GFX prog.": 9,
              "HCI prog.": 5,
              "UX eval.": 2,
              "communication": 2,
              "collaboration": 6,
              "code repository": 10
            },
            {
              
              "Alias": "Terry Boot",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": "Other than technology, my main interests are sports and music. Playing drums and was one of the best sprinters when I was around 15 ",
              "expecting": "How things we see every day on websites and phones actually works. Like parallax etc",
              "InfoVis": 4,
              "statistical": 1,
              "mathematics": 7,
              "artistry": 1,
              "computer usage": 8,
              "programming": 7,
              "GFX prog.": 7,
              "HCI prog.": 7,
              "UX eval.": 8,
              "communication": 9,
              "collaboration": 8,
              "code repository": 4
            },
            {
              
              "Alias": "Lavender Brown",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": "",
              "expecting": "How to represent information more than just a model, how do we enhance the experience? ",
              "InfoVis": 5,
              "statistical": 4,
              "mathematics": 6,
              "artistry": 7,
              "computer usage": 8,
              "programming": 6,
              "GFX prog.": 3,
              "HCI prog.": 7,
              "UX eval.": 7,
              "communication": 5,
              "collaboration": 7,
              "code repository": 6
            },
            {
              
              "Alias": "Millicent Bulstrode",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": "Sports, ",
              "expecting": "I am hopeful that I can use the knowledge I gain throughout this course to be able to better identify good and bad visualization and as well as deceitful diagrams.",
              "InfoVis": 1,
              "statistical": 5,
              "mathematics": 5,
              "artistry": 4,
              "computer usage": 4,
              "programming": 3,
              "GFX prog.": 3,
              "HCI prog.": 4,
              "UX eval.": 8,
              "communication": 8,
              "collaboration": 9,
              "code repository": 4
            },
            {
              
              "Alias": "Charity Burbage",
              "Degree": "Master in Science",
              "Major": "Visual Media",
              "interest, hobbies": "My hobbies are photography, graphic design, over-organising my life (and not necessarily follow up on everything), binge watching netflix original series and cooking.",
              "expecting": "I expect to learn how to ask the right questions and to use some of the available programs to visualize data. I expect I will use this knowledge forever in communicating various things, hopefully in my future work but also for fun in other contexts.",
              "InfoVis": 3,
              "statistical": 2,
              "mathematics": 4,
              "artistry": 8,
              "computer usage": 3,
              "programming": 2,
              "GFX prog.": 1,
              "HCI prog.": 2,
              "UX eval.": 4,
              "communication": 10,
              "collaboration": 9,
              "code repository": 1
            },
            {
              
              "Alias": "Frank Bryce",
              "Degree": "Master in Science",
              "Major": "Human-Computer Interaction",
              "interest, hobbies": "",
              "expecting": "Different methods of visualizing data, approaches how to pick the most suitable \n one, D3.js library usage, see interesting cases. I would like to use it while working as a developer.",
              "InfoVis": 7,
              "statistical": 6,
              "mathematics": 8,
              "artistry": 5,
              "computer usage": 9,
              "programming": 9,
              "GFX prog.": 1,
              "HCI prog.": 6,
              "UX eval.": 5,
              "communication": 5,
              "collaboration": 5,
              "code repository": 10
            },
            {
              
              "Alias": "Alecto Carrow",
              "Degree": "Master in Science",
              "Major": "Human-Computer Interaction",
              "interest, hobbies": "Design piques my interest to no end. From pencil on paper to pixel on screen, from cell in body to brick in building. Apart from designing UI for mobile and web applications, I like to play strategy games, listen music and watch tonnes of tv and movies. ",
              "expecting": "Understanding and Communicating data. It is benefitial when creating platforms and admin panels to properly sort and display information. ",
              "InfoVis": 3,
              "statistical": 4,
              "mathematics": 6,
              "artistry": 9,
              "computer usage": 10,
              "programming": 5,
              "GFX prog.": 2,
              "HCI prog.": 5,
              "UX eval.": 7,
              "communication": 8,
              "collaboration": 8,
              "code repository": 4
            },
            {
              
              "Alias": "Amycus Carrow",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": "training, powerlifting, health, drawing, still photography, photoshop - digital art and retouch, dogs, horses",
              "expecting": "The basics of how to visualize data and develop skill through trial. Create visualizations of complex data to enable communication and understanding. ",
              "InfoVis": 2,
              "statistical": 2,
              "mathematics": 4,
              "artistry": 8,
              "computer usage": 8,
              "programming": 4,
              "GFX prog.": 1,
              "HCI prog.": 4,
              "UX eval.": 4,
              "communication": 9,
              "collaboration": 8,
              "code repository": 5
            },
            {
              
              "Alias": "Reginald Cattermole",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": "I like to play computer games and work out.",
              "expecting": "I expect to learn good ways to visualize different things graphically. I expect to use this in my future line of work.",
              "InfoVis": 4,
              "statistical": 4,
              "mathematics": 5,
              "artistry": 2,
              "computer usage": 8,
              "programming": 5,
              "GFX prog.": 2,
              "HCI prog.": 3,
              "UX eval.": 8,
              "communication": 10,
              "collaboration": 9,
              "code repository": 7
            },
            {
              
              "Alias": "Mary Cattermole ",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": "Computer games, movies, music, motorcycles, drawing, beer",
              "expecting": "To understand and to be able to implement visualization of dynamic data",
              "InfoVis": 5,
              "statistical": 2,
              "mathematics": 4,
              "artistry": 8,
              "computer usage": 9,
              "programming": 8,
              "GFX prog.": 4,
              "HCI prog.": 5,
              "UX eval.": 5,
              "communication": 10,
              "collaboration": 9,
              "code repository": 10
            },
            {
              
              "Alias": "Cho Chang ",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": "I’m mainly a photography and video games nerd, but have an interest in everything media and tech basically. ",
              "expecting": "How to present information (that’s maybe not so easy to interpret and understand) in an attractive and easy-to-understand-way.",
              "InfoVis": 3,
              "statistical": 3,
              "mathematics": 4,
              "artistry": 5,
              "computer usage": 8,
              "programming": 5,
              "GFX prog.": 3,
              "HCI prog.": 4,
              "UX eval.": 2,
              "communication": 8,
              "collaboration": 8,
              "code repository": 6
            },
            {
              
              "Alias": "Penelope Clearwater ",
              "Degree": "Master in Science",
              "Major": "Human-Computer Interaction, Media Technology",
              "interest, hobbies": "Graphic design, photography, hanging at the gym:))",
              "expecting": "How to make cool javascript websites that I can put in my portfolio.. (also maybe how to abstractify complex information in usable ways)",
              "InfoVis": 3,
              "statistical": 4,
              "mathematics": 4,
              "artistry": 7,
              "computer usage": 8,
              "programming": 3,
              "GFX prog.": 1,
              "HCI prog.": 4,
              "UX eval.": 9,
              "communication": 10,
              "collaboration": 8,
              "code repository": 1
            },
            {
              
              "Alias": "Michael Corner",
              "Degree": "Master in Science",
              "Major": "Human-Computer Interaction, Media Technology",
              "interest, hobbies": "I like playing video games, reading(mostly on the internet) and drink beers!",
              "expecting": "How to make dull data ALIVE. On my master thesis or a personal project.",
              "InfoVis": 4,
              "statistical": 3,
              "mathematics": 3,
              "artistry": 2,
              "computer usage": 7,
              "programming": 5,
              "GFX prog.": 3,
              "HCI prog.": 4,
              "UX eval.": 5,
              "communication": 7,
              "collaboration": 8,
              "code repository": 7
            },
            {
              
              "Alias": "Vincent Crabbe",
              "Degree": "Master in Science",
              "Major": "Computer Science",
              "interest, hobbies": "Game development, Japan",
              "expecting": "Learn about how to visualize information, hopefully applicable for games (user interfaces, game GFX).",
              "InfoVis": 4,
              "statistical": 3,
              "mathematics": 5,
              "artistry": 3,
              "computer usage": 8,
              "programming": 10,
              "GFX prog.": 10,
              "HCI prog.": 5,
              "UX eval.": 1,
              "communication": 8,
              "collaboration": 10,
              "code repository": 10
            },
            {
              
              "Alias": "Colin Creevey",
              "Degree": "Master in Science",
              "Major": "Human-Computer Interaction, Graphic Design",
              "interest, hobbies": "I am an aspiring UX/UI designer who loves reading and travelling",
              "expecting": "How to effectively present data and the different methods and tools used. I am planning to become a UX designer, so this course will help me a lot with regarding to my field and interest",
              "InfoVis": 5,
              "statistical": 2,
              "mathematics": 1,
              "artistry": 3,
              "computer usage": 7,
              "programming": 2,
              "GFX prog.": 3,
              "HCI prog.": 4,
              "UX eval.": 8,
              "communication": 9,
              "collaboration": 9,
              "code repository": 1
            },
            {
              
              "Alias": "Fleur Delacour ",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": "Games, drawing (amateur), reading. Interested in technology in all kinds.",
              "expecting": "How to visualize in the best way. Get to know the tools we can use.",
              "InfoVis": 3,
              "statistical": 4,
              "mathematics": 7,
              "artistry": 7,
              "computer usage": 9,
              "programming": 6,
              "GFX prog.": 3,
              "HCI prog.": 2,
              "UX eval.": 7,
              "communication": 8,
              "collaboration": 8,
              "code repository": 5
            },
            {
              
              "Alias": "Amos Diggory",
              "Degree": "Master in Science",
              "Major": "Human-Computer Interaction, Media Technology",
              "interest, hobbies": "When I'm not studying I work at a climbing gym in stockholm (Klätterverket), where I also train ~3 times a week. So what interests me the most it, I would say climbing but I also do love Games (mostly console games) and it's an industry I would love to work in in the future. ",
              "expecting": "The obvious answer is of course to learn more about Information Visualization, but what I expect , and what I want to learn, is how to neatly present complex information. But I also want to learn how to evaluate  data in this form, how do you know what is good/bad, what would make it good/bad etc.. The UX-part is what interest me the most. I would love to be able to use what I have learned in upcoming projects or courses and to further my knowledge in the UX field.",
              "InfoVis": 3,
              "statistical": 2,
              "mathematics": 4,
              "artistry": 7,
              "computer usage": 4,
              "programming": 1,
              "GFX prog.": 1,
              "HCI prog.": 1,
              "UX eval.": 5,
              "communication": 7,
              "collaboration": 4,
              "code repository": 1
            },
            {
              
              "Alias": "Albus Dumbledore",
              "Degree": "Master in Science",
              "Major": "Haven't picked a major yet.",
              "interest, hobbies": "I'm mostly interested in games of different kinds. That's my hobby as well.",
              "expecting": "Hoping to learn some techniques that can be useful for HCI. Regardless, it sounds interesting.",
              "InfoVis": 2,
              "statistical": 1,
              "mathematics": 3,
              "artistry": 5,
              "computer usage": 5,
              "programming": 3,
              "GFX prog.": 1,
              "HCI prog.": 2,
              "UX eval.": 2,
              "communication": 5,
              "collaboration": 5,
              "code repository": 4
            },
            {
              
              "Alias": "Seamus Finnigan",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": "Video production, photography\n\nSports- all kinds of them\n\nCSR - strategies (any kind)\n\nTravel \n\nMusic and stage performance \n\nPublic speaking",
              "expecting": "I expect to become more creative, but also precise, when it comes to backing up a thesis with data (builds logos when presenting). Since I aim at doing more public speaking and presentations I really hope that this course can contribute somehow :) ",
              "InfoVis": 2,
              "statistical": 4,
              "mathematics": 4,
              "artistry": 2,
              "computer usage": 8,
              "programming": 2,
              "GFX prog.": 1,
              "HCI prog.": 1,
              "UX eval.": 8,
              "communication": 10,
              "collaboration": 10,
              "code repository": 4
            },
            {
              
              "Alias": "Marcus Flint",
              "Degree": "Master in Science",
              "Major": "Computer Science",
              "interest, hobbies": "Education, presentation, statistics, language, optimisation, open access, learning",
              "expecting": "I expect to improve my skills in presenting large amounts of data in ways that make people go, \"Aaah, so that's what it means.\" I hope I get to use it at every turn in life! Life is full of terrible presentations of data.",
              "InfoVis": 6,
              "statistical": 4,
              "mathematics": 6,
              "artistry": 3,
              "computer usage": 9,
              "programming": 9,
              "GFX prog.": 7,
              "HCI prog.": 1,
              "UX eval.": 2,
              "communication": 8,
              "collaboration": 4,
              "code repository": 10
            },
            {
              
              "Alias": "Filius Flitwick ",
              "Degree": "Master in Science",
              "Major": "Computer Science",
              "interest, hobbies": "",
              "expecting": "Various data visualisation methods, gain practical experience while doing so and will probably use it in further applications I develop that may require to analyse and show data.",
              "InfoVis": 4,
              "statistical": 7,
              "mathematics": 7,
              "artistry": 5,
              "computer usage": 8,
              "programming": 8,
              "GFX prog.": 5,
              "HCI prog.": 5,
              "UX eval.": 8,
              "communication": 10,
              "collaboration": 8,
              "code repository": 8
            },
            {
              
              "Alias": "Cornelius Fudge",
              "Degree": "Double degree",
              "Major": "Media Technology",
              "interest, hobbies": "",
              "expecting": "Visualization of data - to be uses in the future world",
              "InfoVis": 1,
              "statistical": 6,
              "mathematics": 7,
              "artistry": 1,
              "computer usage": 7,
              "programming": 4,
              "GFX prog.": 5,
              "HCI prog.": 3,
              "UX eval.": 3,
              "communication": 7,
              "collaboration": 8,
              "code repository": 8
            },
            {
              
              "Alias": "Gellert Grindelwald ",
              "Degree": "Master in Science",
              "Major": "Human-Computer Interaction",
              "interest, hobbies": "Design and technology",
              "expecting": "Gain valuable knowledge and tools to use in my future career. Making  presentation of information easy on the eyes. ;-)",
              "InfoVis": 7,
              "statistical": 7,
              "mathematics": 7,
              "artistry": 9,
              "computer usage": 9,
              "programming": 7,
              "GFX prog.": 5,
              "HCI prog.": 7,
              "UX eval.": 8,
              "communication": 9,
              "collaboration": 9,
              "code repository": 6
            },
            {
              
              "Alias": "Godric Gryffindor ",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": "Entrepreneurship. I am currently developing a service for a startup.",
              "expecting": "I hope to learn ways to visualize big data to make it more understandable to \"the naked eye\". I am interested in working with big data in the future, hence I think this course will be very useful for me.",
              "InfoVis": 2,
              "statistical": 3,
              "mathematics": 5,
              "artistry": 6,
              "computer usage": 6,
              "programming": 3,
              "GFX prog.": 1,
              "HCI prog.": 3,
              "UX eval.": 7,
              "communication": 10,
              "collaboration": 10,
              "code repository": 4
            },
            {
              
              "Alias": "Rubeus Hagrid ",
              "Degree": "Master in Science",
              "Major": "Computer Science",
              "interest, hobbies": "Programming, photography, traveling, reading books, hang out family and close friends, workout.",
              "expecting": "How to gather data and present them in the best way possible. This can be useful in the future as we are moving towards an era where Big data is becoming popular. ",
              "InfoVis": 3,
              "statistical": 3,
              "mathematics": 3,
              "artistry": 2,
              "computer usage": 6,
              "programming": 4,
              "GFX prog.": 1,
              "HCI prog.": 3,
              "UX eval.": 2,
              "communication": 10,
              "collaboration": 7,
              "code repository": 3
            },
            {
              
              "Alias": "Rolanda Hooch ",
              "Degree": "Master in Science",
              "Major": "Human-Computer Interaction",
              "interest, hobbies": "",
              "expecting": "I want to learn the coding skills to realize the visualization of information and learn the skill to design an excellent interface for it.",
              "InfoVis": 5,
              "statistical": 6,
              "mathematics": 6,
              "artistry": 8,
              "computer usage": 5,
              "programming": 4,
              "GFX prog.": 4,
              "HCI prog.": 5,
              "UX eval.": 9,
              "communication": 6,
              "collaboration": 7,
              "code repository": 3
            },
            {
              
              "Alias": "Helga Hufflepuff",
              "Degree": "Master in Science",
              "Major": "Human-Computer Interaction",
              "interest, hobbies": "listening to music, reading books, travelling, painting",
              "expecting": "The combination of technology method and the scientific theory of how to realize visualization. In another word, I hope I am able to finish a work on my own after taking this course",
              "InfoVis": 2,
              "statistical": 4,
              "mathematics": 5,
              "artistry": 6,
              "computer usage": 4,
              "programming": 2,
              "GFX prog.": 2,
              "HCI prog.": 3,
              "UX eval.": 4,
              "communication": 8,
              "collaboration": 6,
              "code repository": 2
            },
            {
              
              "Alias": "Hermione Granger",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": "photography, cooking",
              "expecting": "I expect learn more about different methods for visualisation and how to create usable and understandable information systems. I expect to learn this through projects and lectures.",
              "InfoVis": 3,
              "statistical": 3,
              "mathematics": 6,
              "artistry": 4,
              "computer usage": 7,
              "programming": 5,
              "GFX prog.": 1,
              "HCI prog.": 2,
              "UX eval.": 6,
              "communication": 8,
              "collaboration": 8,
              "code repository": 6
            },
            {
              
              "Alias": "Igor Karkaroff ",
              "Degree": "Master in Science",
              "Major": "Human-Computer Interaction, Media Technology",
              "interest, hobbies": "My main interest is computer GFX in all its' forms, mostly targeted towards computer games. I'm also interested in the interaction between humans and computers, how interfaces can be designed and interacted with. \nThe hobbies I have are computer games; especially the puzzle genre. Playing classical guitar is another interest of mine and during summer I enjoy biking. Finally, to watch random YouTube videos is a passion of mine when I have nothing else to do.",
              "expecting": "I expect to learn different methods for visualizing data in order know what to use when. To be able to show the data in a meaningful way tailored to the specific needs of the target audience.",
              "InfoVis": 6,
              "statistical": 4,
              "mathematics": 5,
              "artistry": 5,
              "computer usage": 8,
              "programming": 7,
              "GFX prog.": 7,
              "HCI prog.": 6,
              "UX eval.": 7,
              "communication": 6,
              "collaboration": 7,
              "code repository": 8
            },
            {
              
              "Alias": "Viktor Krum",
              "Degree": "Master in Science",
              "Major": "Human-Computer Interaction",
              "interest, hobbies": "Synthesizers, live music, football, literature",
              "expecting": "how to better understand to visualize data",
              "InfoVis": 3,
              "statistical": 4,
              "mathematics": 2,
              "artistry": 4,
              "computer usage": 6,
              "programming": 1,
              "GFX prog.": 1,
              "HCI prog.": 2,
              "UX eval.": 9,
              "communication": 7,
              "collaboration": 7,
              "code repository": 1
            },
            {
              
              "Alias": "Silvanus Kettleburn ",
              "Degree": "Master in Science",
              "Major": "Human-Computer Interaction, Media Technology",
              "interest, hobbies": "Computer games, food, whiskeys and whines",
              "expecting": "I expect to learn about good tools to use when visualizing data, and also techniques and theory of why you should visualize data in certain ways.",
              "InfoVis": 7,
              "statistical": 6,
              "mathematics": 5,
              "artistry": 3,
              "computer usage": 8,
              "programming": 5,
              "GFX prog.": 5,
              "HCI prog.": 6,
              "UX eval.": 9,
              "communication": 9,
              "collaboration": 10,
              "code repository": 7
            },
            {
              
              "Alias": "Bellatrix Lestrange",
              "Degree": "Master in Science",
              "Major": "Human-Computer Interaction",
              "interest, hobbies": "Painting",
              "expecting": "Learn and use toolkits to filter large data in ways that can enable people to form patterns and find meaning.",
              "InfoVis": 3,
              "statistical": 3,
              "mathematics": 4,
              "artistry": 7,
              "computer usage": 6,
              "programming": 6,
              "GFX prog.": 2,
              "HCI prog.": 2,
              "UX eval.": 7,
              "communication": 8,
              "collaboration": 7,
              "code repository": 7
            },
            {
              
              "Alias": "Neville Longbottom",
              "Degree": "Master in Science",
              "Major": "Human-Computer Interaction",
              "interest, hobbies": "I like to play tennis, I like to coding. I am interested in android development and web development.",
              "expecting": "Alternatives ways of visualising data and better understanding of the data ",
              "InfoVis": 5,
              "statistical": 3,
              "mathematics": 3,
              "artistry": 3,
              "computer usage": 8,
              "programming": 7,
              "GFX prog.": 3,
              "HCI prog.": 6,
              "UX eval.": 5,
              "communication": 8,
              "collaboration": 9,
              "code repository": 8
            },
            {
              
              "Alias": "Xenophilius Lovegood ",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": "Programming, design and photography.",
              "expecting": "How to make active choices around filtering, processing and displaying information to give insights and understand large sets of data.",
              "InfoVis": 6,
              "statistical": 5,
              "mathematics": 5,
              "artistry": 4,
              "computer usage": 9,
              "programming": 8,
              "GFX prog.": 2,
              "HCI prog.": 6,
              "UX eval.": 7,
              "communication": 8,
              "collaboration": 8,
              "code repository": 10
            },
            {
              
              "Alias": "Remus Lupin",
              "Degree": "Master in Science",
              "Major": "Human-Computer Interaction",
              "interest, hobbies": "Startups, self-improvement, sports",
              "expecting": "Practical programming skills in Information Visualization. Building an interactive application.",
              "InfoVis": 7,
              "statistical": 1,
              "mathematics": 4,
              "artistry": 3,
              "computer usage": 8,
              "programming": 6,
              "GFX prog.": 2,
              "HCI prog.": 5,
              "UX eval.": 7,
              "communication": 7,
              "collaboration": 4,
              "code repository": 8
            },
            {
              
              "Alias": "Draco Malfoy",
              "Degree": "Master in Science",
              "Major": "Human-Computer Interaction, Industrial Engineering",
              "interest, hobbies": "Art, music, philosophy, fashion, movies, history, games. I like reading books.",
              "expecting": "How to visualize data, in an informative and easy way for the user to understand. It can probably be used in most cases where something of importance is to be conveyed to a user.",
              "InfoVis": 3,
              "statistical": 3,
              "mathematics": 5,
              "artistry": 4,
              "computer usage": 10,
              "programming": 5,
              "GFX prog.": 2,
              "HCI prog.": 4,
              "UX eval.": 8,
              "communication": 8,
              "collaboration": 9,
              "code repository": 1
            },
            {
              
              "Alias": "Ernie Macmillan",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": "•\tHobbies are playing football, traveling, watching tv, playing video game especially RTS or sandbox genre\n•\tInterest: Augmented Reality, Virtual Reality, Sustainable design, Renewable energy, Interactive Apps, Automatic system, IOT, blogging, comedy writing, startup, walking in new cities\n",
              "expecting": "I would like to learn technical things about information visualization after find website like http://www.gapminder.org/dollar-street",
              "InfoVis": 4,
              "statistical": 5,
              "mathematics": 5,
              "artistry": 4,
              "computer usage": 7,
              "programming": 4,
              "GFX prog.": 4,
              "HCI prog.": 5,
              "UX eval.": 6,
              "communication": 3,
              "collaboration": 6,
              "code repository": 3
            },
            {
              
              "Alias": "Minerva McGonagall",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": "i'm interested in music, i have been producing electronic music for about ten years. Other than that i'm into gaming. ",
              "expecting": "i expect to learn about how to take a pile of data and make sense out of it in different ways. i think this could be useful in several jobs especially with the huge amount of information that is being collected today. ",
              "InfoVis": 2,
              "statistical": 1,
              "mathematics": 5,
              "artistry": 3,
              "computer usage": 6,
              "programming": 3,
              "GFX prog.": 1,
              "HCI prog.": 1,
              "UX eval.": 5,
              "communication": 10,
              "collaboration": 8,
              "code repository": 5
            },
            {
              
              "Alias": "Cormac McLaggen",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": "I like history, development economics, video games and playing football. I also like traveling when my budget and time allows for it. \n\nI listen to A LOT of pod casts as I commute everyday and also hold an Audible subscription.",
              "expecting": "I want to have the ability to make data accessible in manner that allows it to speak a narrative.  One of my favorite subreddits I browse through is \"dataisbeautiful\" and I would very much like to be able to create similar and much better data visualizations. \n\nreddit.com/r/dataisbeautiful/",
              "InfoVis": 3,
              "statistical": 5,
              "mathematics": 3,
              "artistry": 6,
              "computer usage": 8,
              "programming": 4,
              "GFX prog.": 1,
              "HCI prog.": 2,
              "UX eval.": 8,
              "communication": 10,
              "collaboration": 10,
              "code repository": 6
            },
            {
              
              "Alias": "Graham Montague",
              "Degree": "Master in Science",
              "Major": "Computer Science",
              "interest, hobbies": "Listening to lots of music (and making some of my own), playing games and watching horror movies.",
              "expecting": "I want to be able to create neat visualizations from scratch for both my current job (full-stack dev) and in my future career. ",
              "InfoVis": 6,
              "statistical": 4,
              "mathematics": 4,
              "artistry": 5,
              "computer usage": 9,
              "programming": 8,
              "GFX prog.": 7,
              "HCI prog.": 8,
              "UX eval.": 4,
              "communication": 6,
              "collaboration": 9,
              "code repository": 9
            },
            {
              
              "Alias": "Theodore Nott",
              "Degree": "Master in Science",
              "Major": "Computer Science",
              "interest, hobbies": "Traveling, cooking, sleeping, going to concerts (mainly EDM), League of Legends, reading",
              "expecting": "I expect to learn different ways to visualize multi-dimensional data. Also, create  a story from data and analyze other visualizations.",
              "InfoVis": 3,
              "statistical": 8,
              "mathematics": 8,
              "artistry": 3,
              "computer usage": 7,
              "programming": 7,
              "GFX prog.": 3,
              "HCI prog.": 6,
              "UX eval.": 3,
              "communication": 7,
              "collaboration": 8,
              "code repository": 8
            },
            {
              
              "Alias": "Garrick Ollivander ",
              "Degree": "Master in Science",
              "Major": "Computer Science",
              "interest, hobbies": "Doing my masters in CS, here at KTH. I enjoy programming and problem solving in general. Other hobbies include going to the movies, exercising (gym and running), reading, video games and drinking good beer with good friends :)",
              "expecting": "Acquire the skills required to organize, plan and implement a project in data visualization, both for personal interest (e.g. hobby projects) as well as for potential professional purposes. ",
              "InfoVis": 3,
              "statistical": 4,
              "mathematics": 6,
              "artistry": 2,
              "computer usage": 7,
              "programming": 7,
              "GFX prog.": 1,
              "HCI prog.": 3,
              "UX eval.": 4,
              "communication": 8,
              "collaboration": 7,
              "code repository": 6
            },
            {
              
              "Alias": "Pansy Parkinson",
              "Degree": "Master in Science",
              "Major": "Vehicle Engineering",
              "interest, hobbies": "Care about cars, motorsport, football, science, reading and lately world affairs. Have been part of Formula Student teams for 3 years now, also a member at KTH. Data analytics interests me a lot but I am from a mechanical background and the last time I looked at a code was in the first year bachelor (compulsory C course) and high school..!",
              "expecting": "The motivation for joining the course is exactly what its intended outcomes state, so pretty much precisely that, nothing more to add. I would like to use the skills I gain in racecar data analysis and visualization.",
              "InfoVis": 2,
              "statistical": 6,
              "mathematics": 5,
              "artistry": 6,
              "computer usage": 9,
              "programming": 1,
              "GFX prog.": 1,
              "HCI prog.": 1,
              "UX eval.": 3,
              "communication": 7,
              "collaboration": 9,
              "code repository": 4
            },
            {
              
              "Alias": "Peter Pettigrew ",
              "Degree": "Master in Science",
              "Major": "Human-Computer Interaction, Graphic Design",
              "interest, hobbies": "Background in mathematics and have work experience as UX designer,  I have huge passion for combining data and visuality.  The miraculous, gorgeous but unknowable always attract to me.",
              "expecting": "1.Methods of designing information visualization, and techniques of development. But the most attractive is know the boundary of visualization I can do. \n2.Implementing some small projects sounds good. A designer with two developer.",
              "InfoVis": 7,
              "statistical": 4,
              "mathematics": 4,
              "artistry": 10,
              "computer usage": 9,
              "programming": 3,
              "GFX prog.": 3,
              "HCI prog.": 3,
              "UX eval.": 7,
              "communication": 3,
              "collaboration": 6,
              "code repository": 3
            },
            {
              
              "Alias": "Antioch Peverell",
              "Degree": "Bachelor in Science",
              "Major": "Computer Science",
              "interest, hobbies": "",
              "expecting": "I expect to learn how to present data in a informative and easy to understand way for users. I expect to use Information Visualization in my career.",
              "InfoVis": 1,
              "statistical": 1,
              "mathematics": 3,
              "artistry": 1,
              "computer usage": 4,
              "programming": 3,
              "GFX prog.": 1,
              "HCI prog.": 2,
              "UX eval.": 2,
              "communication": 5,
              "collaboration": 5,
              "code repository": 3
            },
            {
              
              "Alias": "Irma Pince",
              "Degree": "Master in Science",
              "Major": "Computer Science, Media Technology, I'm in the media technology program but switched over to computer science master.",
              "interest, hobbies": "Computer games, VR, soccer, ping-pong and swimming.",
              "expecting": "I expect to learn various visualisation techniques and how to apply them in my future field of work. ",
              "InfoVis": 2,
              "statistical": 4,
              "mathematics": 6,
              "artistry": 1,
              "computer usage": 7,
              "programming": 5,
              "GFX prog.": 1,
              "HCI prog.": 1,
              "UX eval.": 4,
              "communication": 8,
              "collaboration": 8,
              "code repository": 3
            },
            {
              
              "Alias": "Sturgis Podmore ",
              "Degree": "Master in Science",
              "Major": "Computer Science",
              "interest, hobbies": "",
              "expecting": "I think one important goal of visualising data is to show the data in a easy way that any type of user can query it and get answers. I expect this course give me the ability to understand how to choose the best design for different type of data. ",
              "InfoVis": 7,
              "statistical": 3,
              "mathematics": 3,
              "artistry": 1,
              "computer usage": 10,
              "programming": 7,
              "GFX prog.": 1,
              "HCI prog.": 5,
              "UX eval.": 4,
              "communication": 10,
              "collaboration": 10,
              "code repository": 10
            },
            {
              
              "Alias": "Poppy Pomfrey ",
              "Degree": "Master in Science",
              "Major": "Computer Science",
              "interest, hobbies": "Before KTH I studied massage therapy among other things. After a while I asked my brother what I could study while also being able to pay off the student debt. He suggested CS and I went back to school to learn math. Today I really enjoy math, data, programming and a lot of other things I've learned along the way. \n\nI enjoy having friends over and playing board games. When I find the time and money for it we enjoy traveling as well.",
              "expecting": "I expect to learn the framework d3 and the principles that go into selecting and presenting graphical models to illustrate different datasets.",
              "InfoVis": 2,
              "statistical": 5,
              "mathematics": 4,
              "artistry": 3,
              "computer usage": 3,
              "programming": 3,
              "GFX prog.": 1,
              "HCI prog.": 2,
              "UX eval.": 1,
              "communication": 6,
              "collaboration": 4,
              "code repository": 4
            },
            {
              
              "Alias": "Harry Potter ",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": "Gaming and weightlifting is what keeps me going to 8 o'clock lectures ",
              "expecting": "To learn meshing and how to create objects in software like blender or unreal engine",
              "InfoVis": 1,
              "statistical": 3,
              "mathematics": 5,
              "artistry": 3,
              "computer usage": 7,
              "programming": 3,
              "GFX prog.": 1,
              "HCI prog.": 5,
              "UX eval.": 6,
              "communication": 10,
              "collaboration": 10,
              "code repository": 7
            },
            {
              
              "Alias": "James Potter ",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": "Music, gaming",
              "expecting": "Learn how to visualize information in an effective manner, including interaction with the information.",
              "InfoVis": 1,
              "statistical": 4,
              "mathematics": 4,
              "artistry": 3,
              "computer usage": 8,
              "programming": 3,
              "GFX prog.": 1,
              "HCI prog.": 3,
              "UX eval.": 9,
              "communication": 9,
              "collaboration": 5,
              "code repository": 3
            },
            {
              
              "Alias": "Lily Potter",
              "Degree": "Master in Science",
              "Major": "Human-Computer Interaction",
              "interest, hobbies": "UI/UX Design, human-computer interaction, research, art, photography, museums, hiking, camping, kayaking, tech",
              "expecting": "To learn how to visualize a large amount if data in a user-friendly way. This knowledge could be applied in arranging and communicating information in an effective way when designing interactive systems.",
              "InfoVis": 2,
              "statistical": 1,
              "mathematics": 2,
              "artistry": 10,
              "computer usage": 9,
              "programming": 2,
              "GFX prog.": 1,
              "HCI prog.": 2,
              "UX eval.": 10,
              "communication": 9,
              "collaboration": 10,
              "code repository": 1
            },
            {
              
              "Alias": "Quirinus Quirrell",
              "Degree": "Master in Science",
              "Major": "Computer Science",
              "interest, hobbies": "Reading, Scuba Dive, walking in forest.",
              "expecting": "I wana be a Data storyteller in future and l believe this course is going to help me in that way.",
              "InfoVis": 1,
              "statistical": 1,
              "mathematics": 3,
              "artistry": 5,
              "computer usage": 5,
              "programming": 5,
              "GFX prog.": 1,
              "HCI prog.": 1,
              "UX eval.": 5,
              "communication": 8,
              "collaboration": 8,
              "code repository": 6
            },
            {
              
              "Alias": "Helena Ravenclaw",
              "Degree": "Master in Science",
              "Major": "Human-Computer Interaction",
              "interest, hobbies": "Big fan of watching TV series, travelling and drinking wine. ",
              "expecting": "I hope to learn more visualisation programming since I lack a bit in that skill, and to earn some skill in how to create nice looking stuff. One day I wish to work with  UX and I think this course will give me a good merit.",
              "InfoVis": 5,
              "statistical": 2,
              "mathematics": 6,
              "artistry": 5,
              "computer usage": 8,
              "programming": 2,
              "GFX prog.": 1,
              "HCI prog.": 2,
              "UX eval.": 7,
              "communication": 9,
              "collaboration": 9,
              "code repository": 5
            },
            {
              
              "Alias": "Rowena Ravenclaw",
              "Degree": "Master in Art",
              "Major": "Media Technology",
              "interest, hobbies": "I'm new to this field, I'll do my best to catch on :)",
              "expecting": "Digital aspects about art, such as animation",
              "InfoVis": 1,
              "statistical": 1,
              "mathematics": 4,
              "artistry": 6,
              "computer usage": 4,
              "programming": 1,
              "GFX prog.": 1,
              "HCI prog.": 1,
              "UX eval.": 7,
              "communication": 7,
              "collaboration": 7,
              "code repository": 3
            },
            {
              
              "Alias": "Tom Marvolo Riddle",
              "Degree": "Master in Science",
              "Major": "Computer Science",
              "interest, hobbies": "I enjoy drawing, 3D modelling and game development in my spare time. I also enjoy watching movies, playing video games and spending time with friends.",
              "expecting": "I expect that I'll learn what makes it easy to understand things that may be difficult to interpret without abstraction. I want to assess this knowledge in order to more effectively convey my ideas and my thoughts to others.",
              "InfoVis": 5,
              "statistical": 5,
              "mathematics": 6,
              "artistry": 9,
              "computer usage": 8,
              "programming": 5,
              "GFX prog.": 4,
              "HCI prog.": 3,
              "UX eval.": 2,
              "communication": 5,
              "collaboration": 6,
              "code repository": 4
            },
            {
              
              "Alias": "Demelza Robins ",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": "Interests:\n• Sustainability (Environment)\n• UX & HCI\n• prog.",
              "expecting": "Tools & knowledge on how to make sense & represent data in a user friendly way",
              "InfoVis": 3,
              "statistical": 5,
              "mathematics": 6,
              "artistry": 8,
              "computer usage": 9,
              "programming": 7,
              "GFX prog.": 2,
              "HCI prog.": 7,
              "UX eval.": 8,
              "communication": 8,
              "collaboration": 8,
              "code repository": 6
            },
            {
              
              "Alias": "Augustus Rookwood",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": " Comedy series, dogs and cooking",
              "expecting": "Learn new and good ways of representing data. And explore how the same data can be visualized and interpreted in different ways. ",
              "InfoVis": 2,
              "statistical": 3,
              "mathematics": 5,
              "artistry": 6,
              "computer usage": 7,
              "programming": 4,
              "GFX prog.": 3,
              "HCI prog.": 7,
              "UX eval.": 7,
              "communication": 10,
              "collaboration": 8,
              "code repository": 7
            },
            {
              
              "Alias": "Thorfinn Rowle ",
              "Degree": "Master in Science",
              "Major": "Computer Science, Media Technology",
              "interest, hobbies": "I've recently discovered an interest in UX, HCI, and computer security. In my free time I enjoy sailing and skiing.",
              "expecting": "I expect to learn different ways of presenting information, more sophisticated than the methods I've used previously, and I expect to be able to use such skills in future projects and work, both at KTH and after KTH.",
              "InfoVis": 2,
              "statistical": 2,
              "mathematics": 3,
              "artistry": 6,
              "computer usage": 7,
              "programming": 7,
              "GFX prog.": 1,
              "HCI prog.": 3,
              "UX eval.": 5,
              "communication": 10,
              "collaboration": 10,
              "code repository": 6
            },
            {
              
              "Alias": "Albert Runcorn",
              "Degree": "Master in Science",
              "Major": "Computer Science",
              "interest, hobbies": "My academic interests are towards statistics and machine learning. My hobbies are music and outdoorsy stuff such as rock climbing and hiking. ",
              "expecting": "I expect to learn many different methods of visualising data in clever ways, especially in an interactive manner. I expect to be confident what visualization tools are at hand and what techniques I should use when faced with a dataset to make it visually appealing and intuitive. ",
              "InfoVis": 3,
              "statistical": 6,
              "mathematics": 5,
              "artistry": 1,
              "computer usage": 7,
              "programming": 5,
              "GFX prog.": 1,
              "HCI prog.": 3,
              "UX eval.": 3,
              "communication": 8,
              "collaboration": 8,
              "code repository": 6
            },
            {
              
              "Alias": "Newt Scamander ",
              "Degree": "Bachelor in Science",
              "Major": "Computer Science, Electrical Engineering",
              "interest, hobbies": "table tennis, photography, reading (myth, sci-fi)",
              "expecting": "Learn how to express my thought (or research consequence) to others using comprehensive visualization techniques. And I believe it cannot only rely on my own intuition, so I want to learn some principles through the course and earn some experience through project.",
              "InfoVis": 3,
              "statistical": 4,
              "mathematics": 6,
              "artistry": 1,
              "computer usage": 3,
              "programming": 5,
              "GFX prog.": 1,
              "HCI prog.": 3,
              "UX eval.": 1,
              "communication": 3,
              "collaboration": 3,
              "code repository": 6
            },
            {
              
              "Alias": "Rufus Scrimgeour ",
              "Degree": "Master in Science",
              "Major": "Computer Science, Media Technology",
              "interest, hobbies": "Food, friends, startup, wine",
              "expecting": "Presenting/Sale via data, in business and education.   ",
              "InfoVis": 2,
              "statistical": 3,
              "mathematics": 5,
              "artistry": 7,
              "computer usage": 8,
              "programming": 7,
              "GFX prog.": 3,
              "HCI prog.": 6,
              "UX eval.": 6,
              "communication": 8,
              "collaboration": 9,
              "code repository": 5
            },
            {
              
              "Alias": "Kingsley Shacklebolt",
              "Degree": "Master in Science",
              "Major": "Computer Science",
              "interest, hobbies": "Music, film, games",
              "expecting": "Visualizing data clearly and effectively",
              "InfoVis": 4,
              "statistical": 6,
              "mathematics": 5,
              "artistry": 3,
              "computer usage": 5,
              "programming": 7,
              "GFX prog.": 2,
              "HCI prog.": 4,
              "UX eval.": 2,
              "communication": 7,
              "collaboration": 7,
              "code repository": 6
            },
            {
              
              "Alias": "Stanley Shunpike",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": "I have a big interest in languages (not programming languages hehe, spoken ones), food, culture, sustainability..",
              "expecting": "To show information in a detailed visual way which is understandable to everybody but also to understand the different methods that are used when visualizing information and understand how to analyze what is showed to me. ",
              "InfoVis": 1,
              "statistical": 2,
              "mathematics": 5,
              "artistry": 6,
              "computer usage": 5,
              "programming": 1,
              "GFX prog.": 1,
              "HCI prog.": 2,
              "UX eval.": 6,
              "communication": 10,
              "collaboration": 10,
              "code repository": 1
            },
            {
              
              "Alias": "Aurora Sinistra",
              "Degree": "Master in Science",
              "Major": "Computer Science",
              "interest, hobbies": "DataViz, Startups, Innovation, Art",
              "expecting": "I would like to learn how to convey facts in the most efficient and entertaining way. I would definitely use it as a final step in any data analysis.",
              "InfoVis": 9,
              "statistical": 6,
              "mathematics": 7,
              "artistry": 8,
              "computer usage": 10,
              "programming": 7,
              "GFX prog.": 5,
              "HCI prog.": 7,
              "UX eval.": 6,
              "communication": 3,
              "collaboration": 2,
              "code repository": 9
            },
            {
              
              "Alias": "Rita Skeeter ",
              "Degree": "Master in Science",
              "Major": "Computer Science",
              "interest, hobbies": "I'm a master of computer science in interaction design track. I'm interested in pc games especially simulation games, sports especially basketball,  history especially ancient times, and new technology in daily life.",
              "expecting": "I want to know the many different ways of information visualization. Also, how to present the data in the right way which means what the audience want to know from the data? I think it is important to visualize information clearly and suitably for audiences. Moreover, I want to apply what I learned on web and mobile applications.",
              "InfoVis": 1,
              "statistical": 6,
              "mathematics": 5,
              "artistry": 1,
              "computer usage": 10,
              "programming": 6,
              "GFX prog.": 1,
              "HCI prog.": 5,
              "UX eval.": 5,
              "communication": 7,
              "collaboration": 8,
              "code repository": 6
            },
            {
              
              "Alias": "Horace Slughorn",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": "In my free time I often play multiplayer games with friends (or less frequently singelplayer games). Look at series and movies - both live action and animated. I did read a lot a few years ago, but can't really find the time nowadays. I'm also a music enthusiast and like the most genres. When I don't do anything of the above I look at streams à la Youtube or Twitch. ",
              "expecting": "I expect to learn neat ways of visualizing information and what to think about when doing it. \n\nWeird as I am, I sort my files and like to have a 'beautiful' structure in my computers hard drives, and when I stumble upon visualizations of large quantities of data on the internet I get really fascinated, I also like to keep track and visualize things in excel sheets. What I try to say is that I think this course is for me, and that is will be a lot of fun. The need for information visualization only increases the more data we produce, and as I'm interesed in the subject I most likely will use information visualization independent of where I'll work or what I'll work with. ",
              "InfoVis": 2,
              "statistical": 2,
              "mathematics": 4,
              "artistry": 5,
              "computer usage": 7,
              "programming": 3,
              "GFX prog.": 2,
              "HCI prog.": 3,
              "UX eval.": 6,
              "communication": 7,
              "collaboration": 6,
              "code repository": 5
            },
            {
              
              "Alias": "Salazar Slytherin",
              "Degree": "Master in Science",
              "Major": "Human-Computer Interaction",
              "interest, hobbies": "Drawing, traveling, learning anything that I find interesting to learn and most of the time I am interested in too many things so I feel like I might need more than 24 hours in a day :s",
              "expecting": "expecting to learn how to present my data effectively so that people would understand it at first sight. I m expecting to use theses skills in business but also in my future tech presentations",
              "InfoVis": 2,
              "statistical": 3,
              "mathematics": 7,
              "artistry": 10,
              "computer usage": 8,
              "programming": 5,
              "GFX prog.": 1,
              "HCI prog.": 3,
              "UX eval.": 10,
              "communication": 8,
              "collaboration": 8,
              "code repository": 5
            },
            {
              
              "Alias": "Hepzibah Smith",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": "Family, friends, traveling, music and training",
              "expecting": "New cool things whitin visualization ",
              "InfoVis": 3,
              "statistical": 3,
              "mathematics": 5,
              "artistry": 3,
              "computer usage": 9,
              "programming": 5,
              "GFX prog.": 5,
              "HCI prog.": 8,
              "UX eval.": 8,
              "communication": 10,
              "collaboration": 9,
              "code repository": 5
            },
            {
              
              "Alias": "Severus Snape",
              "Degree": "Master in Science",
              "Major": "Computer Science",
              "interest, hobbies": "I enjoy traveling and especially skiing. I like nature and people.",
              "expecting": "To evaluate data and be able to determine the best way to visualize it.",
              "InfoVis": 3,
              "statistical": 4,
              "mathematics": 5,
              "artistry": 3,
              "computer usage": 8,
              "programming": 5,
              "GFX prog.": 1,
              "HCI prog.": 2,
              "UX eval.": 4,
              "communication": 8,
              "collaboration": 7,
              "code repository": 4
            },
            {
              
              "Alias": "Pomona Sprout",
              "Degree": "Master in Science",
              "Major": "Computer Science",
              "interest, hobbies": "skateboarding, music and art",
              "expecting": "To use a huge amount of information and present it in a very clear  and interactive way. I expect to maybe use it when working in the future.",
              "InfoVis": 2,
              "statistical": 4,
              "mathematics": 5,
              "artistry": 6,
              "computer usage": 8,
              "programming": 6,
              "GFX prog.": 3,
              "HCI prog.": 2,
              "UX eval.": 2,
              "communication": 7,
              "collaboration": 9,
              "code repository": 4
            },
            {
              
              "Alias": "Dean Thomas",
              "Degree": "Master in Science",
              "Major": "Telecommunications Engineering ",
              "interest, hobbies": "I have always been interested in representing thoughts and emotions through images or music. Photography, painting and playing the piano are my hobbies. But as an engineer, I have also a special interest for every graphical representation of data and that is why I was looking forward for this course.",
              "expecting": "I expect this course to teach me techniques and tools for building aesthetic and practical visualizations for any data that needs to be represented. I have always been interested in the representations of any kind of information, so I expect that after finishing this course I will be able to have experience and a critical thinking about this topic. I am sure I will make use of it in my future career.",
              "InfoVis": 5,
              "statistical": 8,
              "mathematics": 5,
              "artistry": 8,
              "computer usage": 7,
              "programming": 5,
              "GFX prog.": 1,
              "HCI prog.": 5,
              "UX eval.": 5,
              "communication": 3,
              "collaboration": 6,
              "code repository": 5
            },
            {
              
              "Alias": "Nymphadora Tonks ",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": "I'm interested in new media art, music, science and programming.\nMy hobbies are: GFX programming, biking, and listening to music.",
              "expecting": "I expect to learn D3.js and to be able to have good ideas when I need to visually represent data.\nI expect to use the knowledge when working in the industry or in personal projects.",
              "InfoVis": 3,
              "statistical": 2,
              "mathematics": 4,
              "artistry": 4,
              "computer usage": 6,
              "programming": 4,
              "GFX prog.": 4,
              "HCI prog.": 2,
              "UX eval.": 2,
              "communication": 6,
              "collaboration": 5,
              "code repository": 5
            },
            {
              
              "Alias": "Emmeline Vance",
              "Degree": "Master in Science",
              "Major": "Computer Science",
              "interest, hobbies": "Family and friends, sports, nature, food, party",
              "expecting": "How to visualize data, both the technical parts of it but also the interaction part. Get more and/or new programming skills",
              "InfoVis": 2,
              "statistical": 3,
              "mathematics": 5,
              "artistry": 5,
              "computer usage": 3,
              "programming": 4,
              "GFX prog.": 1,
              "HCI prog.": 4,
              "UX eval.": 4,
              "communication": 6,
              "collaboration": 7,
              "code repository": 2
            },
            {
              
              "Alias": "Ron Weasley",
              "Degree": "Master in Science",
              "Major": "Human-Computer Interaction",
              "interest, hobbies": "Playing Video Games",
              "expecting": "Data Analysis and proper structuring of the data",
              "InfoVis": 2,
              "statistical": 4,
              "mathematics": 3,
              "artistry": 3,
              "computer usage": 6,
              "programming": 2,
              "GFX prog.": 2,
              "HCI prog.": 6,
              "UX eval.": 6,
              "communication": 6,
              "collaboration": 6,
              "code repository": 1
            },
            {
              
              "Alias": "Oliver Wood",
              "Degree": "Master in Science",
              "Major": "Media Technology",
              "interest, hobbies": "Hockey, soccer, mma, darts, movies. ",
              "expecting": "Not sure. Hopefully improve my presentation skills among other things. ",
              "InfoVis": 2,
              "statistical": 6,
              "mathematics": 2,
              "artistry": 2,
              "computer usage": 3,
              "programming": 1,
              "GFX prog.": 1,
              "HCI prog.": 2,
              "UX eval.": 6,
              "communication": 5,
              "collaboration": 8,
              "code repository": 2
            }
    ];